### ISSUE TITLE
Naming empty blocks and refactoring sessions

### ISSUE THREAD

**Issue by kirbyfan64** [unisonweb/platform#12]
Firstly, this project's ideas are really neat! I find that I often start editing code, only to forgot what I was doing. My idea is the ability to name empty sections of code (I *know* Unison has a word for placeholders, but I forgot it) and refactoring sessions. That would make things a bit easier!

**Comment by pchiusano** [comment]
Yes, we will definitely support this stuff in some fashion. I'm going to close this issue for now, though. Feel free to stop by the [gitter channel](https://gitter.im/unisonweb/platform) if you have other ideas for stuff. :)
