### ISSUE TITLE
Do you think this project could collect more money to push it forward if it was written on Scala?

### ISSUE THREAD

**Issue by Sergey80** [unisonweb/platform#15]
Question really.

Just wondering. Would it be good reason to start writing this project on Scala. It is not that I want sabotage it on any way (or to be a troll) - more just personal wonder. But I guess the author of FP on Scala might show nice example of what might be done in scala, and I believe there will be much more people willing to contribute or argue to/on this project that seems has nice ideas in it anyway, to push it forward. Or Scala is not good enough for that type of project not FP-pure enough maybe.

**Comment by JustusAdam** [comment]
Mostly probably not performant enough. Scala has bad optimisation problems. No tail call recursion. Plus it runs on the JVM and not in "native" code. 

Technically maybe. But the effort required would not justify it, I think, even *if* Scala was an equally good choice from a performance standpoint.

**Comment by int-index** [comment]
https://reddit.com/r/haskell/comments/1pjjy5/odersky_the_trouble_with_types_strange_loop_2013/cd3bgcu

**Comment by pchiusano** [comment]
The project won't be switching to Scala. Maybe it would attract more attention if it used Scala, dunno, but I much prefer using Haskell for a project like this. Let's just leave it at that. :)
