### ISSUE TITLE
Some issues with new nix build

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/platform#18]
Hi @Ericson2314 it is possible I am doing something wrong, but I am having some issues with the new setup. First one is that `node` does not build:

```
$ cd node
$ nix-shell
...
Preprocessing test suite 'spec' for unix-time-0.3.4...
[1 of 2] Compiling UnixTimeSpec     ( test/UnixTimeSpec.hs, dist/build/spec/spec-tmp/UnixTimeSpec.dyn_o )
test/UnixTimeSpec.hs:62:48:
    Ambiguous occurrence ‘defaultTimeLocale’
    It could refer to either ‘Data.Time.defaultTimeLocale’,
                             imported from ‘Data.Time’ at test/UnixTimeSpec.hs:8:1-16
                             (and originally defined in ‘time-1.5.0.1:Data.Time.Format.Locale’)
                          or ‘System.Locale.defaultTimeLocale’,
                             imported from ‘System.Locale’ at test/UnixTimeSpec.hs:14:23-39
```

Other issue is I'm not sure how to actually build `editor` once I'm in the shell:

```
$ cd ..
$ cd editor
$ nix-shell -A ghcjs
building path(s) ‘/nix/store/iypm6m009l4m3mg8fy224fxab6z4vvnl-head-hash.nix’

[nix-shell:~/Dropbox/projects/unison/editor]$ cabal configure
Warning: The package list for 'hackage.haskell.org' is 37.1 days old.
Run 'cabal update' to get the latest list of available packages.
Resolving dependencies...
Configuring unison-editor-0.1...
cabal: At least the following dependencies are missing:
reflex -any, reflex-dom -any, unison-shared -any
```

But when I did `nix-shell -A ghcjs` for the first time, I saw it successfully build `unison-shared`, `reflex`, and `reflex-dom`. Not sure why cabal is not finding it.

Any help would be greatly appreciated!

**Comment by Ericson2314** [comment]
1. I got that same error and mentioned it in the PR, but perhaps not loud enough. I have no idea, that package shouldn't be built any differently from before.

2. I think you are trying to do a ghc-build with cabal when you have only installed the package for ghcjs. try `cabal configure --ghcjs`, that worked for me.

**Comment by pchiusano** [comment]
Thanks for the quick reply! I missed your original note on the broken `node` build, my bad. :)

`cabal configure --ghcjs` worked in the editor directory and your explanation makes sense.

I could have sworn I had `node` building before via nix, using [this version of nixpkgs](https://github.com/NixOS/nixpkgs/tree/9205d01e1e3b945e0bace8a99e157e96550b9055), but I just tried supplying that version explicitly via `nix-shell -I /path/to/nixpkgs` and get the same error.

Going to leave this open until one of us can figure out what's going on with the `node/` build.

**Comment by pchiusano** [comment]
Googling around, looks like this is a known issue: 

https://github.com/kazu-yamamoto/unix-time/issues/30

And it looks like there is a fix in latest nixpkgs: https://github.com/NixOS/nixpkgs/blame/ea3382bb69e542b7af7cdc1407abd9e0dc757c68/pkgs/development/haskell-modules/configuration-ghc-7.10.x.nix#L117

Now, I am not sure why that override to not run tests for that package isn't being used. Am guessing there is some tweak we could make to `env.nix`?

**Comment by Ericson2314** [comment]
At work again, so can't offer too much help, but https://github.com/unisonweb/try-reflex/blob/master/nixpkgs/default.nix decides what version of nixpkgs to import. Ideally you can one that works, or worst case you'll have to override unix-time either in our try-reflex's `deps/default.nix` or platform's `env.nix`.

**Comment by pchiusano** [comment]
If we wanted to modify platform's `env.nix`, how would we do that exactly? I think the version of nixpkgs is okay, we just need to specify that the unix-time tests should not be run when building. I am guessing that we want to do the equivalent of:

```
unix-time = dontCheck super.unix-time;
```

... somewhere?

**Comment by Ericson2314** [comment]
Trying that in topic/nix. Unfortunately `env.nix` is somewhat over-abstract so it is not obvious where that goes.

**Comment by Ericson2314** [comment]
Ah, so since repeated overriding doesn't work in pure-darwin, this needs to be solved in our try-reflex fork. My work-around in `env.nix` does not work for transitive dependencies.

**Comment by pchiusano** [comment]
Okay, cool. I had tried a couple variations of adding another override here:

https://github.com/unisonweb/platform/blob/master/env.nix#L32

... without success, and I was modifying code I didn't really understand so figured I'd let you take a look.

Something I noticed is that unix-time 0.3.5 has since been released, and the latest nixpkgs has that version listed here: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/haskell-modules/hackage-packages.nix

So you could either get everything working with the latest (or a more recent) nixpkgs, or add the override in our try-reflex fork. I don't really have a preference on which one, whichever is easier.

**Comment by Ericson2314** [comment]
I overrode it in try-reflex, but then wai-extras was not compiling due to `-Werror`.

**Comment by pchiusano** [comment]
Hey @Ericson2314 am back from vacation. I see you got everything working. :) I pushed some fixes to the node build itself, and it builds cleanly for me, including dependencies. I didn't totally follow your explanation here: https://gitter.im/unisonweb/platform?at=5590ac19a3aa0fa2043c67f4 

I'm going to open up a new issue to track a few other stuff related to the build, basically testing that this works for linux, updating the README, etc. Thanks for your work on this!
