### ISSUE TITLE
Test, cleanup, and document project build instructions

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/platform#19]
I'd like to get a few things cleaned up with the new build:

* Add an install-nix.sh script to this repo for installing nix. (Crib from try-reflex)
* Add a [vagrant setup file](https://www.vagrantup.com/) to this repo for setting up a valid linux dev box for this project. Use this box for testing the build on linux, and it'll also be useful if there's any devs on Windows who want to work on the project.
* Once we have these, and assuming everything works:
  * Delete the existing `SETUP.sh` and shared sandboxes stuff. 
  * Update README with build instructions.

Build instructions shouldn't assume any knowledge of nix, cabal, or even Haskell. A monkey should be able to follow the instructions and know at the end whether they have a working setup. For example:

```
$ git clone https://github.com/unisonweb/platform.git unison
$ cd unison
$ # if you don't already have Nix package manager installed
$ ./nix-install.sh
# you'll be prompted to install nix package manager
$ cd node
$ nix-shell
# wait a while
$ cabal configure
$ cabal test
... # if all goes well
Test suite tests: RUNNING...
Test suite tests: PASS
Test suite logged to: dist/test/unison-node-0.1-tests.log
1 of 1 test suites (1 of 1 test cases) passed.
```

@Ericson2314 I can take care of the README updates, but do you think you could test out the build on Linux inside a Vagrant environment? Assuming that works, we can check in the vagrantfile.

**Comment by pchiusano** [comment]
Also, @Ericson2314 after this we should find something more interesting for you to work on, I know this is not super exciting. :) I might have some ideas.

**Comment by kirbyfan64** [comment]
Wait: does this mean Nix will now be required to use Unison?

**Comment by pchiusano** [comment]
@kirbyfan64 no definitely not. Unison should be usable on just about any platform. Nix would just be required for development of Unison. And we are talking about Nix the package manager, not Nix the OS.

**Comment by pchiusano** [comment]
@Ericson2314 okay, so current status is:

* Build works on mac (or at least on my machine!), but waiting to hear from @joshcough who is trying it from fresh install.
* Build does not work on linux. On the vagrant box I tried, I didn't even get as far as a successful install of Nix (see below), and apparently even after that it tries to compile the entire universe instead of getting binary caches. I think this is the most pressing issue, we really should have a working build on mac AND linux.
* You had some suggestions for updating the instructions and using nix-build, and also for switching the vagrant box to NixOS. Please go for it!

Since I have a working build on mac, I'm going to focus on writing some real code for a bit. :) I'm hoping you can get build stuff sorted soon. Please let me know if I can help, though, or if you are just sick of working on it and would like to pass the torch to me or someone else. :)

Btw, here is the error I was getting, if we are switching the vagrant box to nixos, then it doesn't really matter, but just fyi -

```
$ vagrant up
...
==> default: error: the group ‘nixbld’ specified in ‘build-users-group’ does not exist
==> default: nix-binary-tarball-unpack/nix-1.9-x86_64-linux/install: unable to install Nix into your default profile
...
$ vagrant ssh
vagrant@vagrant-ubuntu-trusty-64:~$ cd /vagrant/node
vagrant@vagrant-ubuntu-trusty-64:/vagrant/node$ ./shell.nix
./shell.nix: line 1: syntax error near unexpected token `.unisonPackages.ghc7101.unison-node.env'
./shell.nix: line 1: `(import ../env.nix).unisonPackages.ghc7101.unison-node.env'
```

**Comment by joshcough** [comment]
I did not get around to trying it last night, but will definitely tonight.

**Comment by kirbyfan64** [comment]
@pchiusano I think you need to run [`nix-shell`](http://nixos.org/nix/manual/#sec-nix-shell) instead of just `./shell.nix`...

**Comment by pchiusano** [comment]
@kirbyfan64 ha, you are right. I meant to type `shell.sh` there. Trying again now...

**Comment by pchiusano** [comment]
Hmm, it looks like nix-shell did not even end up on the path after the install. Based on the warning message, I'm guessing it just didn't get added and I need to do it manually. I gotta work on other stuff right now but maybe will take a look later.

**Comment by pchiusano** [comment]
Going to close this and reopen a ticket just tracking the vagrant box setup.
