### ISSUE TITLE
rename

### ISSUE THREAD

**Issue by fryguybob** [unisonweb/platform#2]
I was browsing the code and came across this line in [`ABT.rename`]:

    Var v -> if v == old then var new else var old

Shouldn't the else case be `var v`?

[`ABT.rename`]: https://github.com/unisonweb/platform/blob/master/node/src/Unison/ABT.hs#L89

**Comment by pchiusano** [comment]
Wow, yes. Perhaps some tests would be a good idea. :)

**Comment by pchiusano** [comment]
Btw, @fryguybob congrats on making the first official bug report for this project! :) There might be a few other bugs with the new ABT-based representation of terms/types, as that was just switched over in the last couple weeks and I have not banged on it much. If you or anyone else is interested, writing some tests for the typechecker might be a fun (depending on your definition) way to get your feet wet with the codebase. :)
