### ISSUE TITLE
shell.sh: dependencies couldn't be built

### ISSUE THREAD

**Issue by dansherpa** [unisonweb/platform#33]
[shell.sh.log.txt](https://github.com/unisonweb/platform/files/42019/shell.sh.log.txt)
Running shell.sh on OS/X to build for the first time, eventually I fail with:

`error: build of ‘/nix/store/lz7449yjaa07qn3h9z8lkqk9pgn4rlk3-bash-4.3-p33.drv’ failed
/Users/danik/.nix-profile/bin/nix-shell: failed to build all dependencies
[shell.sh.log.txt](https://github.com/unisonweb/platform/files/42017/shell.sh.log.txt)`

I've attached the full log from my most recent attempt.

**Comment by pchiusano** [comment]
Hmm, looks like Ryan's cache is/was down? I just pinged him on IRC, will see what he says.

**Comment by pchiusano** [comment]
I think this should be addressed now that build is converted to Stack, #34, but if you have trouble please reopen or post a new issue with any troubles you have.
