### ISSUE TITLE
Screenshots for the README.md

### ISSUE THREAD

**Issue by alistra** [unisonweb/platform#4]
Please provide some project screenshots, so somebody can see the effect without setting up everything.

A live demo would be fine too.

**Comment by anko** [comment]
There's a vid on [Paul's blog][1] and lots of text.

(Def +1 for linking it from the README though.)

[1]: http://pchiusano.github.io/2015-03-17/unison-update5.html

**Comment by pchiusano** [comment]
Okay, I added a couple links to the README, including link to a video. It's too bad the README can't embed the video directly or I'd just do that.

A live demo might be fun, I'll give that some thought.
