### ISSUE TITLE
The search fails with 500 "Internal Server Error"

### ISSUE THREAD

**Issue by int-index** [unisonweb/platform#8]
Expected behaviour: functions can be used, autocompletion works.
Actual behaviour: no functions are available, thus no autocompletion too.

Steps to reproduce:

1.   Run the server with `cabal run node`
2.   Run the editor with `elm-reactor` and opening `http://localhost:8000/src/Unison/Editor.elm`
3.   Literals (numbers, strings) can be entered, but there are no available functions.
4.   Open the developer console. The error manifests as follows:
```
POST http://localhost:8080/search 500 (Internal Server Error)
error: BadResponse 500 ("Internal Server Error")
```

**Comment by int-index** [comment]
Apparentely, the server fails in `Unison.NodeServer.runN` while running `liftIO (unnote n)`.

**Comment by int-index** [comment]
So I messed around with the `search` definition in `Unison.Node.Implementation`. For some reason it gets some trash values in `hs` on the following line:
```haskell
hs <- Store.hashes store Nothing
```

In my case, printing 'show hs` results in the following:
```haskell
fromList [,(),Color.rgba,Fixity.InfixL,Fixity.InfixR,Fixity.Prefix,Metadata.metadata,Number.divide,Number.minus,Number.times,Symbol.Symbol,Text.center,Text.concatenate,Text.justify,Text.left,Text.right,Vector.append,Vector.concatenate,Vector.empty,Vector.map,Vector.prepend,Vector.single,View.cell,View.color,View.declare,View.embed,View.fit-width,View.function1,View.hide,View.horizontal,View.reactive,View.source,View.spacer,View.swatch,View.text,View.textbox,View.vertical,View.view,#",#_zQnO]
```

The empty term (which is actually `Reference.Builtin ""`) and `#"` and `#_zQnO` (which are some hashes) are the trashy ones. Filtering them out fixes evenything. The question is: where do they come from? I did not modify the store in any way.

**Comment by pchiusano** [comment]
Okay, that is very helpful, will try to repro and look into this.

**Comment by pchiusano** [comment]
Weird, I cannot reproduce. I just rebuilt with the new fixed stackage deps. Can you try doing `rm -rf node/store` and a clean build? Also what OS are you using?

**Comment by int-index** [comment]
Running `rm -rf` did help this one time, but it didn't help the last time I ran it. There appears to be some non-determenism, and that's weird. I'm using Gentoo.

**Comment by int-index** [comment]
No, forget it. It worked because of my temporary fix (filtering out trash values). I forgot to revert it. Running `rm -rf` has no effect whatsoever.

**Comment by pchiusano** [comment]
Weird. If you ls -a, do those files exist in any of the directories? We could add a filter for ends in `.json` [here](https://github.com/unisonweb/platform/blob/master/node/src/Unison/Node/Store.hs#L43), perhaps that would do it:

```
    hashesIn :: (String -> Reference) -> FilePath -> Noted IO (Set Reference)
    hashesIn f dir = Note.lift $
      -- the `drop 2` strips out '.' and '..', gak
      Set.fromList . (map (f . reverse . drop 5 . reverse) . drop 2) <$> -- strip out .json
        Directory.getDirectoryContents (root </> dir)
```

Still a mystery to me why `getDirectoryContents` would be returning that extra junk for you.

**Comment by int-index** [comment]
>  -- the `drop 2` strips out '.' and '..', gak

I mean, really? That's obvious now. On my system `getDirectoryContents` does not return them as two first elements. Just replace this hack with `filter (/=".") . filter (/="..")` or something similar. Works for me.

**Comment by pchiusano** [comment]
Yeah pretty janky. Not sure what I was thinking. :/ I think a better filter
is just only include files ending in .json. I'll make the change tomorrow
if you don't beat me to it with a PR.

I'd also like to have a better data store than this silly file based one.
